version: "3"

services:
  statsd-metrics-generator:
    image: fsferrara/statsd-metrics-generator
    links:
      - graphite-statsd
    environment:
      STATSD_HOST: graphite-statsd

  graphite-statsd:
    image: hopsoft/graphite-statsd
    ports:
      - 80:80
      - 81:81
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
